var ANIMAL_WORDS = [
  'Dolphin', 
  'Capybara', 
  'Giraffee', 
  'Alligator', 
  'Catipiller', 
  'Kangaroo', 
  'Iguana', 
  'Hamster', 
  'Elephant',
  'Tortoise', 
  'Flamingo', 
  'Monkey', 
  'Chipmunk',
  'Porcupine', 
  'Jaguar', 
  'Wombat', 
  'Meerkat', 
  'Hedgehog', 
  'Squirrel',
  'Armadillo',
  'Axolotl',
  'Chicken',
  'Chihuahua',
  'Cricket',
  'Crayfish',
  'Dalmatian',
  'Dragonfly',
  'Dormouse',
  'Eskipoo',
  'Flounder',
  'Greyhound',
  'Hippopotamus',
  'Jellyfish',
  'Leopard',
  'Ladybug',
  'Labradoodle',
  'Lobster',
  'Narwhal',
  'Numbat',
  'Octopus',
  'Opossum',
  'Penguin',
  'Pelican',
  'Pigeon',
  'Platypus',
  'Quokka',
  'Rhinoceros',
  'Raccoon',
  'Samoyed',
  'Stingray',
  'Starfish',
  'Swordfish',
  'Salamander',
  'Toadfish',
  'Utonagan',
  'Vulture',
  'Weasel',
  'Walrus',
  'Xerus',
  'Yoranian',
  'Zonkey'
  ];

  ANIMAL_WORDS = ANIMAL_WORDS.map(word => word.toUpperCase())
  
  function randomWord() {
    return ANIMAL_WORDS[Math.floor(Math.random() * ANIMAL_WORDS.length)];
  }
  
  export { randomWord };